CREATE DATABASE FilmMagic;
GO

USE FilmMagic;
GO


CREATE TABLE Cliente(
Id INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(50) NOT NULL,
Telefono VARCHAR(14) NOT NULL,
Cedula VARCHAR(11) UNIQUE NOT NULL,
Estado BIT DEFAULT 1 NOT NULL
);
GO


CREATE TABLE Producto(
Id INT IDENTITY(1,1) PRIMARY KEY,
Descripcion VARCHAR (50) NOT NULL,
PrecioUnitario DECIMAL(10,4) NOT NULL,
Extento BIT DEFAULT 1 NOT NULL,
Estado BIT DEFAULT 1 NOT NULL,
CantidadEnStock INT NOT NULL
);

GO

CREATE TABLE Alquiler(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdCliente INT FOREIGN KEY REFERENCES Cliente(Id) NOT NULL, 
IdProducto INT FOREIGN KEY REFERENCES Producto(Id) UNIQUE NOT NULL,
CantidadAlquilada INT NOT NULL,
FechaInicial DATETIME NOT NULL,
FechaFinal DATETIME NOT NULL,
PrecioUnitarioProducto DECIMAL(10,4)  NOT NULL,
TotalItbis DECIMAL(10,4) NOT NULL,
SubTotal  DECIMAL(10,4) NOT NULL,
);
GO

CREATE TABLE Devolucion(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdAlquiler INT FOREIGN KEY REFERENCES Alquiler(Id) UNIQUE NOT NULL,
MontoPorAtraso DECIMAL(10,4) NOT NULL,
NotaAtraso VARCHAR(50),
);
GO

CREATE TABLE Usuario(
Id INT IDENTITY(1,1) PRIMARY KEY,
Avatar VARCHAR(200) UNIQUE NOT NULL,
Clave VARCHAR(MAX),
Nombre VARCHAR(20), 
);
GO


DROP TABLE Devolucion;
DROP TABLE Alquiler;






