//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmMagic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        public int Id { get; set; }
        public int IdAlquiler { get; set; }
        public decimal MontoPorAtraso { get; set; }
        public string NotaAtraso { get; set; }
    
        public virtual Alquiler Alquiler { get; set; }
    }
}
